# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 714056c1bfb93fb6913984dbe0dcf0d22a23ac8e91569c12add9f4f059397a1cdeb1a0f19a0a32f5a246a2bcb9334524b31dd3d6c554c1d97588611ff7598266

test:
  secret_key_base: d5e0ca65dfecc221b5c4404cb48e1728a0ee6701705e5fa6fbf0b3fc98a231d7fdf072332ab1476fa69c7e6b3118b11068373978792ee0d384d0110827eb9a91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
